sudo: required
services:
  - docker

before_install:
  - docker build -t xscotophilic/docker-multicontainer-complex-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xscotophilic/docker-multicontainer-complex-app npm run test

after_success:
  - docker build -t xscotophilic/docker-multicontainer-complex-app-client ./client
  - docker build -t xscotophilic/docker-multicontainer-complex-app-nginx ./nginx
  - docker build -t xscotophilic/docker-multicontainer-complex-app-server ./server
  - docker build -t xscotophilic/docker-multicontainer-complex-app-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xscotophilic/docker-multicontainer-complex-app-client
  - docker push xscotophilic/docker-multicontainer-complex-app-nginx
  - docker push xscotophilic/docker-multicontainer-complex-app-server
  - docker push xscotophilic/docker-multicontainer-complex-app-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-626478535714
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
